import Link from "next/link"
import { ArrowLeft, ArrowRight } from "lucide-react"

export const metadata = {
  title: "Global Leadership Community Case Study | AeroRev",
  description: "How we built a dual-pipeline HubSpot system with custom API integration to Outseta, automating memberships and events for a global leadership community.",
}

export default function GlobalLeadershipCommunityCaseStudy() {
  return (
    <div className="flex flex-col">
      {/* Back Link */}
      <div className="pt-32 pb-8">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <Link href="/case-studies" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Case Studies
          </Link>
        </div>
      </div>

      {/* Hero */}
      <section className="pb-16">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-wrap gap-2 mb-6">
            <span className="px-3 py-1 text-xs font-medium bg-muted text-muted-foreground">HubSpot</span>
            <span className="px-3 py-1 text-xs font-medium bg-muted text-muted-foreground">Outseta</span>
            <span className="px-3 py-1 text-xs font-medium bg-muted text-muted-foreground">Stripe</span>
            <span className="px-3 py-1 text-xs font-medium bg-muted text-muted-foreground">Custom API</span>
            <span className="px-3 py-1 text-xs font-medium bg-muted text-muted-foreground">Membership</span>
          </div>
          
          <h1 className="font-heading text-4xl sm:text-5xl font-bold text-foreground leading-tight mb-6">
            Global Leadership Community: Membership + Events Automation
          </h1>
          
          <p className="text-xl text-muted-foreground leading-relaxed">
            International leadership organization running memberships and high-end adventure events. We built two automated pipelines in HubSpot, integrated Outseta via custom API, and automated tier-based pricing across Stripe.
          </p>
        </div>
      </section>

      {/* Metrics */}
      <section className="py-16 bg-secondary/30">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="text-4xl font-heading font-bold text-foreground mb-2">2</div>
              <div className="text-sm text-muted-foreground">Automated Pipelines</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-heading font-bold text-foreground mb-2">3+</div>
              <div className="text-sm text-muted-foreground">Platforms Synced</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-heading font-bold text-foreground mb-2">0</div>
              <div className="text-sm text-muted-foreground">Manual Billing Steps</div>
            </div>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-16">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="prose prose-lg max-w-none">
            <h2 className="font-heading text-3xl font-bold text-foreground mb-6">The Problem</h2>
            <p className="text-muted-foreground leading-relaxed mb-6">
              This global leadership community brings together entrepreneurs, executives, and change-makers through annual memberships and high-end adventure experiences (think Kilimanjaro treks, Arctic expeditions, leadership retreats).
            </p>
            <p className="text-muted-foreground leading-relaxed mb-6">
              They had two separate business models running simultaneously:
            </p>
            <ul className="space-y-3 mb-6">
              <li className="text-muted-foreground"><strong>Memberships:</strong> Applicants go through human review, get assigned to tiers (Veteran vs Virgin Striver, with age-based discounts), sign up through Outseta, and pay recurring fees</li>
              <li className="text-muted-foreground"><strong>Events:</strong> Members and non-members apply for specific adventure experiences, pricing varies by tier and event, payment links generated via Stripe</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mb-12">
              Everything was manual. Applications came in via forms. Staff manually reviewed them. Payment links were generated by looking up pricing in spreadsheets. Billing contacts were handled via email threads. The team was drowning in admin work.
            </p>

            <h2 className="font-heading text-3xl font-bold text-foreground mb-6">The Technical Challenges</h2>
            
            <h3 className="font-heading text-xl font-semibold text-foreground mb-4">1. No Native HubSpot ↔ Outseta Integration</h3>
            <p className="text-muted-foreground leading-relaxed mb-6">
              Outseta is their membership portal where people sign up and pay. Once someone becomes a paying member in Outseta, that status needed to sync back to HubSpot automatically to trigger welcome emails and update contact records. There's no native connector. We had to build a custom API integration.
            </p>

            <h3 className="font-heading text-xl font-semibold text-foreground mb-4">2. Membership Tiers With Human Review</h3>
            <p className="text-muted-foreground leading-relaxed mb-6">
              Membership isn't open to everyone. Applicants go through a vetting process. The team manually reviews each application and assigns the correct tier (Veteran member, Virgin Striver, under-35 discount, etc.). Once assigned, all downstream communication and pricing must reflect that tier automatically.
            </p>

            <h3 className="font-heading text-xl font-semibold text-foreground mb-4">3. Event Pricing Varies By Tier AND By Event</h3>
            <p className="text-muted-foreground leading-relaxed mb-6">
              Members pay different rates than non-members. And those rates vary event by event. The system needed to identify the applicant's tier, match it to the specific event they applied for, generate the correct Stripe payment link, and send it automatically.
            </p>

            <h3 className="font-heading text-xl font-semibold text-foreground mb-4">4. Billing Contacts (Third-Party Payers)</h3>
            <p className="text-muted-foreground leading-relaxed mb-12">
              Event applicants could nominate someone else to receive the payment link and handle billing. The system needed to create a separate billing contact record, send them the payment link, and associate them back to the original applicant.
            </p>

            <h2 className="font-heading text-3xl font-bold text-foreground mb-6">What We Built</h2>

            <h3 className="font-heading text-2xl font-bold text-foreground mb-4 mt-8">Pipeline 1: Membership Applications</h3>
            <p className="text-muted-foreground leading-relaxed mb-6">
              <strong>Flow:</strong>
            </p>
            <ol className="space-y-3 mb-6 list-decimal list-inside">
              <li className="text-muted-foreground">Application submitted via HubSpot form → Creates contact and deal in "Membership Applications" pipeline</li>
              <li className="text-muted-foreground">Team reviews applicant → Manually assigns membership tier (custom property)</li>
              <li className="text-muted-foreground">Tier assignment triggers workflow → Sends personalized email with link to Outseta membership portal</li>
              <li className="text-muted-foreground">Applicant signs up and pays in Outseta</li>
              <li className="text-muted-foreground">Custom API syncs Outseta → HubSpot → Updates contact record with payment status</li>
              <li className="text-muted-foreground">Payment confirmation triggers welcome email sequence in HubSpot</li>
            </ol>

            <h3 className="font-heading text-2xl font-bold text-foreground mb-4 mt-8">Pipeline 2: Event Applications</h3>
            <p className="text-muted-foreground leading-relaxed mb-6">
              <strong>Flow:</strong>
            </p>
            <ol className="space-y-3 mb-6 list-decimal list-inside">
              <li className="text-muted-foreground">Event application submitted → Creates contact and deal in "Event Applications" pipeline</li>
              <li className="text-muted-foreground">Workflow checks eligibility (age, membership status, event capacity)</li>
              <li className="text-muted-foreground">If billing contact specified → Creates separate contact record and associates it via contact-to-contact association</li>
              <li className="text-muted-foreground">Workflow identifies applicant tier + specific event → Generates correct Stripe payment link via custom property logic</li>
              <li className="text-muted-foreground">Payment link sent to billing contact (or applicant if no billing contact)</li>
              <li className="text-muted-foreground">Payment confirmation syncs back → Triggers dual confirmation emails (applicant + billing contact)</li>
            </ol>

            <h3 className="font-heading text-2xl font-bold text-foreground mb-4 mt-8">Custom API Integration (Outseta ↔ HubSpot)</h3>
            <p className="text-muted-foreground leading-relaxed mb-6">
              Built a custom API integration to sync membership payment status from Outseta back to HubSpot in real time:
            </p>
            <ul className="space-y-3 mb-12">
              <li className="text-muted-foreground">Reads account-level membership data from Outseta API</li>
              <li className="text-muted-foreground">Matches to correct HubSpot contact via email address</li>
              <li className="text-muted-foreground">Updates custom properties in HubSpot (membership status, tier, payment date)</li>
              <li className="text-muted-foreground">Triggers automated welcome sequence once payment confirmed</li>
            </ul>

            <h3 className="font-heading text-2xl font-bold text-foreground mb-4 mt-8">Tier-Based Pricing Logic</h3>
            <p className="text-muted-foreground leading-relaxed mb-6">
              Created a matrix of custom properties to handle tier + event pricing:
            </p>
            <ul className="space-y-3 mb-12">
              <li className="text-muted-foreground">Each event has custom pricing fields for each tier (Veteran Member, Virgin Member, Under-35, Non-Member)</li>
              <li className="text-muted-foreground">Workflow reads applicant tier + selected event → Pulls correct price → Generates Stripe link</li>
              <li className="text-muted-foreground">New events are added by populating pricing fields once; workflow logic handles everything else</li>
            </ul>

            <h2 className="font-heading text-3xl font-bold text-foreground mb-6">The Results</h2>
            <p className="text-muted-foreground leading-relaxed mb-6">
              <strong>Full membership lifecycle automated:</strong> From application to tier assignment to Outseta signup to HubSpot sync to welcome email. The team only touches the approval decision.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-6">
              <strong>Pricing errors eliminated:</strong> Tier-to-event pricing is handled by workflow logic, not by someone looking up a spreadsheet and manually creating payment links.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-6">
              <strong>Billing contacts automated:</strong> Third-party payers are created as separate contact records, receive payment links automatically, and are associated back to the applicant for tracking.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-12">
              <strong>Referral tracking built in:</strong> Contact-to-contact associations capture who referred whom, making referral data searchable and reportable.
            </p>

            <h2 className="font-heading text-3xl font-bold text-foreground mb-6">Technical Stack</h2>
            <ul className="space-y-3 mb-6">
              <li className="text-muted-foreground"><strong>HubSpot (Sales + Operations Hubs)</strong> - Dual pipelines, contact management, workflow automation</li>
              <li className="text-muted-foreground"><strong>Outseta</strong> - Membership portal and recurring billing</li>
              <li className="text-muted-foreground"><strong>Stripe</strong> - Event payment processing</li>
              <li className="text-muted-foreground"><strong>Custom API</strong> - Syncs Outseta membership status → HubSpot</li>
              <li className="text-muted-foreground"><strong>HubSpot Forms</strong> - Application intake for both memberships and events</li>
            </ul>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 bg-card border-y border-border">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="font-heading text-3xl font-bold text-foreground mb-4">Running memberships, events, or multi-tier pricing?</h2>
          <p className="text-lg text-muted-foreground mb-8">
            We build HubSpot systems that automate complex workflows and integrate platforms that don't talk to each other.
          </p>
          <Link href="/contact" className="btn-primary">
            Book a Call
            <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </div>
      </section>
    </div>
  )
}
